---

- src: https://github.com/snipem/commute-tube
  branch: master
  docdir: .
  targetdir: commute

- src: https://github.com/snipem/psnprices
  branch: master
  docdir: .
  targetdir: psnprices

- src: https://github.com/mundimark/awesome-markdown
  branch: master
  docdir: .
  targetdir: awesome-markdown

# - src: git@github.com:bodiam/awesome-asciidoc.git
#   branch: master
#   docdir: .
#   targetdir: awesome-asciidoc

- src: https://github.com/arc42/arc42-template
  branch: master
  # hugo does not support relative includes as of now
  docdir: EN/asciidoc/src
  targetdir: arc42