---

- src: https://github.com/snipem/monako
  branch: develop
  docdir: .
  targetdir: docs/monako

- src: https://github.com/snipem/commute-tube
  branch: master
  docdir: .
  targetdir: docs/commute

- src: https://github.com/snipem/psnprices
  branch: master
  docdir: .
  targetdir: docs/psnprices

- src: https://github.com/mundimark/awesome-markdown
  branch: master
  docdir: .
  targetdir: docs/awesome-markdown

- src: https://github.com/snipem/maniacforum.git
  branch: master
  docdir: .
  targetdir: docs/maniacforum

# - src: git@github.com:bodiam/awesome-asciidoc.git
#   branch: master
#   docdir: .
#   targetdir: awesome-asciidoc

- src: https://github.com/arc42/arc42-template
  branch: master
  # hugo does not support relative includes as of now
  docdir: EN/asciidoc/src
  targetdir: docs/arc42