---
  whitelist:
    - ".md"
    - ".adoc"
    - ".jpg"
    - ".jpeg"
    - ".svg"
    - ".gif"
    - ".png"

  origins:
  - src: https://github.com/snipem/monako
    branch: develop
    docdir: .
    targetdir: docs/monako

  - src: https://github.com/snipem/commute-tube
    branch: master
    docdir: .
    targetdir: docs/commute

  - src: https://github.com/snipem/psnprices
    branch: master
    docdir: .
    targetdir: docs/psnprices

  - src: https://github.com/mundimark/awesome-markdown
    branch: master
    docdir: .
    targetdir: docs/awesome-markdown

  - src: https://github.com/snipem/maniacforum.git
    branch: master
    docdir: .
    targetdir: docs/maniacforum

  - src: https://github.com/asciidoctor/asciidoctor-diagram.git
    branch: master
    docdir: examples
    targetdir: docs/asciidoctor-diagram
