---
  baseURL : "https://example.com/"
  title : "My Projects"
  logo : "docs/monako/profile.png"

  disableCommitInfo: false

  whitelist:
    - ".md"
    - ".adoc"
    - ".jpg"
    - ".jpeg"
    - ".svg"
    - ".gif"
    - ".png"

  origins:

  - src: https://github.com/snipem/monako-test
    branch: master
    docdir: .
    targetdir: docs/monako
    blacklist:
      - "example_blacklisted_doc.adoc"

  - src: https://github.com/snipem/commute-tube
    branch: master
    docdir: .
    targetdir: docs/commute

  - src: https://github.com/snipem/psnprices
    branch: master
    docdir: .
    targetdir: docs/psnprices

  - src: https://github.com/mundimark/awesome-markdown
    branch: master
    docdir: .
    targetdir: docs/awesome-markdown

  - src: https://github.com/snipem/maniacforum.git
    branch: master
    docdir: .
    targetdir: docs/maniacforum

  - src: https://github.com/bodiam/awesome-asciidoc.git
    branch: master
    docdir: .
    targetdir: docs/awesome-asciidoc
